/**
 * POST /api/presentation -- Re-generate an HTML5 presentation for an existing run.
 *
 * Presentations are now generated by the pipeline (Phase 4: PRESENT) and
 * saved to public/decks/{runId}.html. This endpoint allows re-generation
 * if the presentation-system.md spec is updated.
 */

import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { present } from "@/lib/pipeline/present";
import type { PipelineEvent } from "@/lib/pipeline/types";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { runId } = body;

    if (!runId) {
      return NextResponse.json({ error: "runId is required" }, { status: 400 });
    }

    // Load run data from database
    const run = await prisma.run.findUnique({
      where: { id: runId },
      include: {
        agents: { include: { findings: true } },
        synthesis: { orderBy: { order: "asc" } },
        dimensions: true,
      },
    });

    if (!run) {
      return NextResponse.json({ error: "Run not found" }, { status: 404 });
    }

    // Reconstruct the data structures needed for present()
    const blueprint = {
      query: run.query,
      dimensions: run.dimensions.map((d) => ({
        name: d.name,
        description: d.description,
        justification: "",
        dataSources: [] as string[],
        lens: "",
        signalMatch: "",
      })),
      agents: run.agents.map((a) => ({
        name: a.name,
        archetype: a.archetype ?? "",
        dimension: a.dimension ?? "",
        mandate: a.mandate ?? "",
        tools: JSON.parse(a.tools ?? "[]") as string[],
        lens: "",
        bias: "",
      })),
      interconnections: [] as { dimensionA: string; dimensionB: string; coupling: number; mechanism: string }[],
      complexityScore: {
        breadth: run.breadth ?? 3,
        depth: run.depth ?? 3,
        interconnection: run.interconnection ?? 3,
        total: run.complexityScore ?? 9,
        urgency: 1.0,
        adjusted: run.complexityScore ?? 9,
        reasoning: "",
      },
      tier: (run.tier ?? "STANDARD") as "MICRO" | "STANDARD" | "EXTENDED" | "MEGA" | "CAMPAIGN",
      estimatedTime: run.estimatedTime ?? "",
      ethicalConcerns: [] as string[],
    };

    const agentResults = run.agents.map((a) => ({
      agentName: a.name,
      archetype: a.archetype ?? "",
      dimension: a.dimension ?? "",
      findings: a.findings.map((f) => ({
        statement: f.statement,
        evidence: f.evidence ?? "",
        confidence: (f.confidence ?? "MEDIUM") as "HIGH" | "MEDIUM" | "LOW",
        sourceTier: (f.sourceTier ?? "SECONDARY") as "PRIMARY" | "SECONDARY" | "TERTIARY",
        evidenceType: (f.evidenceType ?? "inferred") as "direct" | "inferred" | "analogical" | "modeled",
        source: f.source ?? "",
        implication: f.implication ?? "",
        tags: JSON.parse(f.tags ?? "[]") as string[],
      })),
      gaps: [] as string[],
      signals: [] as string[],
      minorityViews: [] as string[],
      toolsUsed: JSON.parse(a.tools ?? "[]") as string[],
      tokensUsed: 0,
    }));

    const synthesis = {
      layers: run.synthesis.map((s) => ({
        name: s.layerName as "foundation" | "convergence" | "tension" | "emergence" | "gap",
        description: s.description,
        insights: JSON.parse(s.insights) as string[],
      })),
      emergentInsights: [] as never[],
      tensionPoints: [] as never[],
      overallConfidence: "MEDIUM" as const,
      criticRevisions: [] as string[],
    };

    const events: PipelineEvent[] = [];
    const presentation = await present({
      synthesis,
      agentResults,
      blueprint,
      emitEvent: (e) => events.push(e),
    });

    // Save to public/decks/
    const decksDir = join(process.cwd(), "public", "decks");
    mkdirSync(decksDir, { recursive: true });
    const filename = `${runId}.html`;
    writeFileSync(join(decksDir, filename), presentation.html, "utf-8");

    // Update or create presentation record
    const existing = await prisma.presentation.findFirst({ where: { runId } });
    if (existing) {
      await prisma.presentation.update({
        where: { id: existing.id },
        data: {
          title: presentation.title,
          subtitle: presentation.subtitle,
          htmlPath: `/decks/${filename}`,
          slideCount: presentation.slideCount,
        },
      });
    } else {
      await prisma.presentation.create({
        data: {
          title: presentation.title,
          subtitle: presentation.subtitle,
          htmlPath: `/decks/${filename}`,
          slideCount: presentation.slideCount,
          runId,
        },
      });
    }

    return NextResponse.json({
      success: true,
      title: presentation.title,
      slideCount: presentation.slideCount,
      htmlPath: `/decks/${filename}`,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
